### ISSUE TITLE
Feature Request: Automated Voting

### ISSUE THREAD

**Issue by caniszczyk** [cncf/gitvote#172]
It would be great if you can have an option in the config file for automated voting so you don't have to manually call "/vote"

Say you can do a pathspec like anything in "docs/" or "README.md" - and a PR affects those files, an automated vote would be called. This is kind of like the GitHub https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners functionality

**Comment by tegioz** [comment]
This is ready @caniszczyk. You can find more details about how it works in the reference config file:

https://github.com/cncf/gitvote/blob/76a3b9a733c380bb8bb89b8100db407bbcfc8735/docs/config/.gitvote.yml#L9-L32

/cc @jeefy
