### ISSUE TITLE
Self-hosted GitVote

### ISSUE THREAD

**Issue by etiennetremel** [cncf/gitvote#231]
Hi there, thanks again for open sourcing this great product.

Currently, I'm seeing the following point that can be improved to make it easier to deploy the Chart:
- public Docker images (gitvote and gitvote-dbmigrator), for now it's publishing to an AWS account
- publish Helm chart in a Helm registry, you can host it on GitHub and it's fairly easy to implement with this actions: https://github.com/helm/chart-releaser-action
- link the Helm Chart to ArtifactHub

I would be happy to support if you have any questions.

**Comment by tegioz** [comment]
Hi @etiennetremel 👋

Thanks, we are glad you like it! This is a great idea, we'll take care of it this week 🙂

@cynthia-sg and I (the maintainers of this project) also maintain Artifact Hub, so thank you as well for promoting its usage, that's very helpful! 😍

**Comment by tegioz** [comment]
This is ready @etiennetremel 🙂🎉

<https://artifacthub.io/packages/helm/gitvote/gitvote>

I've moved some of your notes to the chart's readme file, hope you don't mind 😇
