### ISSUE TITLE
Add GOVERNANCE.md

### ISSUE THREAD

**Issue by caniszczyk** [cncf/gitvote#263]
We should have a governance.md file that lists the maintainers and how to add/remove them

e.g., https://github.com/coredns/coredns/blob/master/GOVERNANCE.md

THEN we should use GitVote itself to respect this governance file

**Comment by caniszczyk** [comment]
or this: https://github.com/containerd/project/blob/main/GOVERNANCE.md

We should also probably have a https://github.com/containerd/project/blob/main/MAINTAINERS file that we add/remove maintainers etc

**Comment by ashutosh887** [comment]
@caniszczyk @tegioz I would like to work on this issue
