### ISSUE TITLE
Feature Request: Auto-close vote once passing

### ISSUE THREAD

**Issue by jeefy** [cncf/gitvote#335]
We should have a config option (`close_on_passing`?) that will automatically close a vote once the passing threshold has been met. 

I think this should default to being `close_on_passing: false`, but for some of the votes (mainly TOC votes) behave such that once a vote has passed, they close the vote rather than leave it open. 

cc @amye

**Comment by tegioz** [comment]
This is ready @amye @jeefy. You can [enable it in the repositories/profiles you'd like](https://github.com/cncf/gitvote/blob/577b335814025f3e23d23996ad1faeb286a23f81/docs/config/.gitvote.yml#L126-L137) by updating the corresponding `.gitvote.yml` file 🙂

*Please note that it'll be enabled only for new votes, not existing ones.*
