### ISSUE TITLE
Adding "vote" label

### ISSUE THREAD

**Issue by mauilion** [cncf/gitvote#396]
I think it would be very helpful if the vote bot could add a label to an issue like "vote open" and then remove that label when voting is closed. This would be useful in filtering issues that are currently open for voting and would reduce the toil of creating a list of open vote issues.

**Comment by tegioz** [comment]
Hi @mauilion 👋

This is ready 🙂

We're adding a `gitvote` label to issues/PRs where a vote was created, plus an addition `vote open` one to issues/PRs where the vote is still open (which we remove once it's closed).

Some sample queries:

- [Votes open on PRs in the cncf/toc repository](https://github.com/search?q=user%3Acncf+repo%3Atoc+label%3Agitvote+label%3A%22vote+open%22&type=pullrequests)
- [Votes open on issues across all repositories in the CNCF org](https://github.com/search?q=user%3Acncf+label%3Agitvote+label%3A%22vote+open%22&type=Issues)

(existing issues have been labelled as well to make this more useful)

Thanks!
