### ISSUE TITLE
See running results

### ISSUE THREAD

**Issue by duglin** [cncf/gitvote#444]
While the /check-vote command is nice, if done too often it'll clutter up the PR comments (both with the /check-vote comment and results comment). It might be nice if stepping into the PR check for GitVote showed the current stats - e.g. this page: https://github.com/cncf/toc/pull/996/checks?check_run_id=19297364452

**Comment by tegioz** [comment]
Hi @duglin 👋

During the duration of a vote, we don't really have any current stats. Reactions accumulate on GitHub and, whenever `/check-vote` command is called or the vote is closed, the bot collects all the information needed, makes its computations, and writes the results on a new comment. One reason it works this way is that we aren't notified on reactions. So to make something like this work, we'd need to be polling periodically. Given the rate limits on the GitHub API, that would impact the amount of votes we can have running at the same time on a given organization. And we'd rather not do that for a non-critical feature.

In addition to that, it's also possible to create votes on issues, where there wouldn't be check runs.

Hope this helps 🙂

**Comment by duglin** [comment]
hmm thanks for the reply. I wonder then if it might be possible to have the /check-vote action delete any old stats comment before it adds a new one? Basically, I'm just looking for a way to reduce the noise in the issue/PR since a long running vote could end up having quite a few of these status comments if people want to check the result often.  Or... what would be really cool is if it updated the original vote comment with the current stats of the vote (even better if it did it via a cron job once a day). Then I wouldn't need to ask, I could just look at the one vote comment and see the current results of the binding voting members (within the 24hr window).

**Comment by tegioz** [comment]
You don't really need to ask, GitVote is able to check periodically and post the results automatically. In the TOC repository, for example, it's configured [to do so every week](https://github.com/cncf/toc/blob/1fb5871d4ce299d330b0a9bd91fc73848bf4da45/.gitvote.yml#L5). Votes sometimes last months, so asking the bot very often doesn't usually help. And you'll get notified as soon as the vote passes anyway.

Updating the original comment was already proposed some time ago, but [it was decided](https://github.com/cncf/gitvote/issues/162#issuecomment-1602832537) that having the original vote comment and the results at the end was useful for auditing purposes. Deleting comments with intermediate results would also alter this audit trail, and would leave orphan `/check-vote` calls comments, which would be weird. Please note that those extra comments are helpful as notifications for all interested parties, and can even act as reminders in some cases (i.e. [users who haven't voted yet are mentioned](https://github.com/cncf/toc/pull/996#issuecomment-1848095166)). So even though I agree they can be noisy, I also think they can be helpful 🙂

**Comment by tegioz** [comment]
Will close this one for now, please feel free to reopen if needed 🙂
