### ISSUE TITLE
Add a third option (abstain) to voting

### ISSUE THREAD

**Issue by jeefy** [cncf/gitvote#48]
Currently we have +1/-1 as options. We should also have an "Active abstain" vote, and then we can report on the % of responders more accurately.

Another way of putting it, we shouldn't assume a no-vote is an abstain.

**Comment by tegioz** [comment]
Hi @jeefy 👋

We already have an abstain option, please see <https://github.com/cncf/gitvote> 🙂

**Comment by tegioz** [comment]
Abstain votes are counted separately than no-vote too 😉

**Comment by jeefy** [comment]
<3 Thanks, I totally missed it!

**Comment by tegioz** [comment]
No worries!
