### ISSUE TITLE
Getting Error teams in allowed voters can only be used in organizations

### ISSUE THREAD

**Issue by AayushSaini101** [cncf/gitvote#480]
I have already setup the config file and passed my username to authorise the vote, still getting, teams in allowed voters can only be used in organizations

This is my public issue: https://github.com/AayushSaini101/Vote/issues/16 and here is my config file https://github.com/AayushSaini101/Vote/blob/main/.gitvote.yml

**Comment by tegioz** [comment]
Hi @AayushSaini101 👋

You can only setup teams allowed to vote when using GitVote within an organization, not in individual accounts.
