### ISSUE TITLE
Policies for who can vote

### ISSUE THREAD

**Issue by domenkozar** [cncf/gitvote#491]
It would be great for https://github.com/NixOS if we could define policies like:

- only this team can vote
- only those with X commits into this repo can vote

This could be defined in `gitvote.yml` via any policy language.

**Comment by tegioz** [comment]
Hi @domenkozar 👋

You should be able [to define what team(s) and/or individual users can vote](https://github.com/cncf/gitvote/blob/e55afaf1e9271fab1041a2aa20cf52bab5df2b9f/docs/config/.gitvote.yml#L66-L95).

At the moment we are trying to keep the tool as simple as possible, so adding more options to define who can vote isn't in our roadmap. Although not ideal, that can always be managed by another process that adds/removes users to/from a team based on the criteria you define.

Hope this helps 🙂
