### ISSUE TITLE
Vote passed worklow not working

### ISSUE THREAD

**Issue by AayushSaini101** [cncf/gitvote#524]
The vote has been passed but the vote closed message not appear:

https://github.com/asyncapi/community/issues/1313#issuecomment-2247419571

<img width="1238" alt="image" src="https://github.com/user-attachments/assets/5730b687-0ada-4b2a-bf78-a23dd6c05bf7">

**Comment by tegioz** [comment]
Hi @AayushSaini101 👋

When `close_on_passing` is enabled, the vote is checked automatically once a day and, if it has passed, the vote is closed. It looks like some of the votes have been submitted in the last 24 hours, so it's likely that it hasn't been checked again yet.

**Comment by AayushSaini101** [comment]
> Hi @AayushSaini101 👋
> 
> When `close_on_passing` is enabled, the vote is checked automatically once a day and, if it has passed, the vote is closed. It looks like some of the votes have been submitted in the last 24 hours, so it's likely that it hasn't been checked again yet.

thanks @tegioz for the instructions :)

**Comment by tegioz** [comment]
No worries! Please let us know if it isn't closed automatically within the next day 😉
